[external]
  [external."nvim"]
  type = "git"
  url = "https://github.com/rslangl/nvim.git"
  refreshPeriod = "168h" 
  dest = "private_dot_config/nvim"

  [external."zsh-autosuggestions"]
  type = "git"
  url = "https://github.com/zsh-users/zsh-autosuggestions.git"
  dest = "private_dot_config/zsh/plugins/zsh-autosuggestions"

  [external."zsh-syntax-highlighting"]
  type = "git"
  url = "https://github.com/zsh-users/zsh-syntax-highlighting.git"
  dest = "private_dot_config/zsh/plugins/zsh-syntax-highlighting"

