#!/bin/sh

# /etc/X11/xinit/xinitrc
#
# global xinitrc file, used by all X sessions started by xinit (startx)

# invoke global X session script
. /etc/X11/Xsession

# start terminal emulator
/usr/bin/X11/rxvt-unicode &

# start window manager
exec /etc/alternatives/x-window-manager

# set background image
#feh --bg-fill $HOME/Pictures/wallpaper/astartes.jpg

