#!/bin/sh

# /etc/X11/xinit/xinitrc
#
# global xinitrc file, used by all X sessions started by xinit (startx)

# invoke global X session script
. /etc/X11/Xsession

# set background image
#xsetbg -fullscreen "$HOME"/Pictures/wallpapers/astartes.jpg &
feh --bg-scale $HOME/Pictures/wallpaper/astartes.jpg

# start terminal emulator
/usr/bin/X11/rxvt-unicode &

# start window manager
exec /etc/alternatives/x-window-manager
