export VCPKG_ROOT="${XDG_DATA_HOME}"/vcpkg

export VAGRANT_HOME="${XDG_DATA_HOME}"/vagrant
export VAGRANT_ALIAS_FILE="${XDG_DATA_HOME}"/vagrant/aliases

export ANSIBLE_HOME="${XDG_CONFIG_HOME}"/ansible
export ANSIBLE_CONFIG="${XDG_CONFIG_HOME}"/ansible/ansible.cfg
export ANSIBLE_GALAXY_CACHE_DIR="${XDG_CACHE_HOME}"/ansible/ansible/galaxy_cache

export DOCKER_CONFIG="${XDG_CONFIG_HOME}"/docker

export KUBECONFIG="${XDG_CONFIG_HOME}"/kube/config
export KUBECACHEDIR="${XDG_CACHE_HOME}/kube"

export XAUTHORITY="${XDG_RUNTIME_DIR}"/Xauthority

export PATH="${PATH}:${HOME}/.local/bin:/usr/local/go/bin:${CARGO_HOME}/bin"

[[ -z $DISPLAY && $XDG_VTNR -eq 1 ]] && startx "${XDG_CONFIG_HOME}"/X11/xinitrc
