if [[ -z "$PATH" || "$PATH" == "/bin:/usr/bin" ]]
then
	export PATH="/usr/local/bin:/usr/bin:/bin:$HOME/.local/bin"
fi

# dotfiles
#export DOTFILES="$HOME/.dotfiles"

# XDG paths
#export XDG_DATA_HOME=${XDG_DATA_HOME:="$HOME/.local/share"}
#export XDG_CACHE_HOME=${XDG_CACHE_HOME:="$HOME/.cache"}
#export XDG_CONFIG_HOME=${XDG_CONFIG_HOME:="$HOME/.config"}
#export XDG_STATE_HOME=${XDG_STATE_HOME:="$HOME/.local/state"}

# XDG system directories
#export XDG_DATA_DIRS=${XDG_DATA_DIRS:="/usr/local/share:/usr/share"}
#export XDG_CONFIG_DIRS=${XDG_CONFIG_DIRS:="/etc/xdg"}

# zsh
export ZDOTDIR="$XDG_CONFIG_HOME"/zsh
export HISTFILE="$XDG_CONFIG_HOME"/zsh/history

# set GO path
export PATH="$PATH:/usr/local/go/bin"
export GOPATH="$XDG_DATA_HOME"/go
export GOMODCACHE="$XDG_CACHE_HOME"/go/mod

# xorg-xauth
export XAUTHORITY="$XDG_RUNTIME_DIR"/Xauthority

# xinit
export XINITRC="$XDG_CONFIG_HOME"/X11/xinitrc
export XSERVERRC="$XDG_CONFIG_HOME"/X11/xserverrc

# Xorg
export USERXSESSION="$XDG_CACHE_HOME/X11/xsession"
export USERXSESSIONRC="$XDG_CACHE_HOME/X11/xsessionrc"
export ALTUSERXSESSION="$XDG_CACHE_HOME/X11/Xsession"
export ERRFILE="$XDG_CACHE_HOME/X11/xsession-errors"

# GnuPG
export GNUPGHOME="$XDG_DATA_HOME"/gnupg

# Set other pahts
export WGETRC="$XDG_CONFIG_HOME"/wget
export RIPGREP_CONFIG_PATH="$XDG_CONFIG_HOME"/ripgrep

# instruct NVIDIA to use custom path
if [ "$(command -v nvidia-setting &> /dev/null)" ];
then
  nvidia-setting --config="$XDG_CONFIG_HOME"/nvidia/settings
fi

# instruct sbt to use custom path
if [ "$(command -v sbt --version &> /dev/null)" ];
then
  sbt -ivy "$XDG_DATA_HOME"/ivy2 -sbt-dir "$XDG_DATA_HOME"/sbt
fi

# instruct ansible to use custom path
if [ "$(command -v ansible &> /dev/null)" ];
then
  export ANSIBLE_HOME="${XDG_CONFIG_HOME}/ansible"
  export ANSIBLE_CONFIG="${XDG_CONFIG_HOME}/ansible/ansible.cfg"
  export ANSIBLE_GALAXY_CACHE_DIR="${XDG_CACHE_HOME}/ansible/ansible/galaxy_cache"
fi

# instruct w3m to use custom path
if [ "$(command -v w3m --version &> /dev/null)" ];
then
  export W3M_DIR="$XDG_STATE_HOME"/w3m
fi

# instruct npm to use custom path
if [ "$(command -v npm --version &> /dev/null)" ];
then
  export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME"/npm/npmrc
fi

# instruct docker to use custom path
if [ "$(command -v docker --version &> /dev/null)" ];
then
   	export DOCKER_CONFIG="$XDG_CONFIG_HOME"/docker
fi

# default apps
export EDITOR="nvim"
export VISUAL="nvim"
export TERMINAL="rxvt-unicode"
export BROWSER="firefox"
