export ZSH="$ZDOTDIR/ohmyzsh"

export HISTFILE="$XDG_CONFIG_HOME"/zsh/history

source $ZSH/custom/aliases.zsh

ZSH_THEME="bureau"

plugins=(
  git
  dotenv
  fzf
  zsh-autosuggestions
  zsh-syntax-highlighting
)

eval "$(zoxide init zsh)" > /dev/null 2>&1
eval "$(ssh-agent -s)" > /dev/null 2>&1

source $ZSH/oh-my-zsh.sh
