export ZSH="$ZDOTDIR/ohmyzsh"

export HISTFILE="$XDG_CONFIG_HOME"/zsh/history

ZSH_THEME="bureau"

plugins=(
  git
  dotenv
  fzf
  zsh-autosuggestions
  zsh-syntax-highlighting
)

eval "$(zoxide init zsh)" > /dev/null 2>&1

eval "$(keychain --absolute --dir $XDG_RUNTIME_DIR/keychain --eval --agents ssh ~/.ssh/github ~/.ssh/norsetech --quiet)"

source $ZSH/oh-my-zsh.sh
